sudo: required
services:
  - docker

before_install:
  - docker build -t sharath717/react-test -f ./client/Dockerfile.dev ./client

scripts:
  - docker run -e CI=true sharath717/react-test npm run test -- --coverage

after_success:
  - docker build -t sharath717/multi-nginx ./nginx
  - docker build -t sharath717/multi-client ./client
  - docker build -t sharath717/multi-server ./server
  - docker build -t sharath717/multi-worker ./worker
  # Log in to docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push sharath717/multi-nginx
  - docker push sharath717/multi-client
  - docker push sharath717/multi-server
  - docker push sharath717/multi-worker
